### PR TITLE
Update Cesium master to latest from AnalyticalGraphics

### PR DESCRIPTION
**Pull request by geoffrowland**

### CODE REVIEW

**Comment by kring** [comment]
Thanks @geoffrowland. As you may know, it's the `terriajs` branch, not master, that we need to merge into for use with TerriaJS. Typically we merge in the latest tagged release rather than master.

So I know you asked me awhile ago about upgrading Cesium, and I'm really sorry I haven't done that yet. Are you already working on it yourself?

**Comment by geoffrowland** [comment]
Thanks @kring. I'm very interested in upgrading the version of CesiumJS, used with TerriaJS, in order to make use of the new high-resolution Cesium World Terrain (1-2 m for much of the UK). Using TerriaMap, with its built-in catalogs and server, is much nicer than using 'raw' CesiumJS and more flexible than just using the Cesium Ion platform.

Have tinkered a little, but all 'somewhat above my pay grade'. Will gratefully and patiently await your work. I guess you will need to put something in place by September when the old STK World Terrain will no longer be available.
https://cesium.com/blog/2018/03/01/introducing-cesium-world-terrain/

Similarly, waiting for 2020 when the Environment Agency should release full-cover 1m LiDAR data for England into the public domain.
https://environmentagency.blog.gov.uk/2017/12/30/uncovering-englands-landscape-by-2020/

**Comment by kring** [comment]
Yeah, we'll need to do something by September, I'm a bit behind the curve on that. You saw this, right?
https://github.com/TerriaJS/terriajs/pull/2994

You can try it out in your own app just by changing the terriajs version in package.json to `TerriaJS/terriajs#cesium-1.46`.  Oh you'll also need to do the following your from app's directory:

```
npm install -g sync-dependencies
sync-dependencies --source terriajs
rm -rf node_modules # assuming you haven't put anything important in there!!
npm install
```

That'll update your app's package.json to use the same Cesium version as TerriaJS (and potentially sync other dependencies as well), and then install them. 

I'd be interested to hear how it works for you.

**Comment by geoffrowland** [comment]
Thanks @kring!!!!

Those instructions work for me. Adding useCesiumIonTerrain: true to the parameters section of config.json displays the Cesium Ion logo and the high resolution World terrain. Similarly, setting my cesiumIonAccessToken hides the license message. Can now see the Dorset and East Devon World Heritage Coast in 3D at 1m resolution (rather than 30 m resolution) in TerriaMap.

So far, the only issue I have found is switching to a custom Cesium Ion terrain rather than the default Cesium World Terrain. I have directly edited TerriaMap.js to change the AssetId from 1 to the relevant value (see below), but just get a 'Terrain Server Not Responding' message. Is there anything else I should do?

```
    function createWorldTerrain(options) {
        options = defaultValue(options, defaultValue.EMPTY_OBJECT);

        return new CesiumTerrainProvider({
            url: IonResource.fromAssetId(1),
            requestVertexNormals: defaultValue(options.requestVertexNormals, false),
            requestWaterMask: defaultValue(options.requestWaterMask, false)
        });
    }
```

Still,  a huge step forward. Again, many thanks

**Pull request merged**
