### PR TITLE
Fix WMS 1.3 getFeatureInfo

### PR DESCRIPTION
**Pull request by zoran995**
Fix for https://github.com/TerriaJS/terriajs/issues/4431

### CODE REVIEW

**Comment by tephenavies** [comment]
Thanks for the fix. I think this should be submitted upstream to Cesium.

**Comment by rowanwins** [comment]
I've been encountering this too. 

TBH it seems kinda weird because from what I can tell both Cesium & Terria ought to be doing GetFeatureInfo requests with WMS version 1.1.1 so I'm not very sure how that version number is being over-ridden.

See [Cesium](https://github.com/CesiumGS/cesium/blob/1.73/Source/Scene/WebMapServiceImageryProvider.js#L684-L688)
And [Terria-Cesium](https://github.com/TerriaJS/cesium/blob/terriajs/Source/Scene/WebMapServiceImageryProvider.js#L684-L688)

Using the [Cesium Sandcastle GetFeatureInfo](https://sandcastle.cesium.com/?src=Web%20Map%20Service%20(WMS).html) requests are made with version 1.1.1 so I'm wondering if something is going on in `next` somewhere...

**Comment by zoran995** [comment]
@rowanwins Terria sends a version parameter in the url, if we do same in the above sandcastle it will send request using version 1.3.0. [sandcastle example](https://sandcastle.cesium.com/#c=bVLRbhoxEPyV1T1UICV2KKAkF6CN0odWStSqSM3LSdVytxwWPvtk+47SiH/vmgNE0jzZO54Zj3fdooNW0YYcTMHQBh7Iq6YSv/ZYL0vyff1gTUBlyGVJ/y4zmZES7osCEJ6f5qAqLMltQeOWGaZlzwP0GBHP1t0d4hXMRq9qgUXxrQN+ONuqIgYwcB7rmRZPWM/JtSqnt9yXSAZonE67HUCWrEKofSqlwaCsQV1hLUrbCmxk7eyfrYwEPi/JerbljOdMo/KAIrdV5DMl2Nr+/ji+Wku78Z98l2PKPfjASs+y6UAMxVWWXHQJ9h3xKef4ui2cLR3Wq226sI78iVOjw4rCnvdyDH6wi8rXjgDBofEsIhNSLho6nSytqzBEzb6vsjblSbeLy66fmdP85gFdALtcgrZ2rUwJGOC+8eyvFQqeYzeznNM5FJ5C/BRdlwvyQXWNSo+z+UncK1NqEktnqy9UOiLf624fDEZifDs4ZLkcjcXN8PpQDUY34vZYXI7F9TBu+wzs+neQXCQTH7aaZsdXflZVbTk5z7knhAxU1RoDeblo8jUFkXsf3xipE3kunRSqBVVM3/nUkGv0nk+WjdZz9ZeyZDaRzP9Pqi0W3KvvPCAebqStBrPHDhRCTCSX7yuDtXqB7o3zPw) - this server somehow support `x,y` parameters for wms 1.3.0. 

Just found out that this can be resolved by adding `version` to `queryParametersToRemove` list in wms ([here](https://github.com/TerriaJS/terriajs/blob/next/lib/Models/WebMapServiceCatalogItem.ts#L878-L887)), but still think that it is better to submit a fix to cesium.

**Comment by zoran995** [comment]
I have created a PR on Cesium for this #9143

**Comment by zoran995** [comment]
Closing as it is resolved on cesium end. It is included in the latest release (1.74).

**Pull request closed without merging**
